version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: course-postgres-db
    environment:
      POSTGRES_USER: dbUser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: coursesdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: course-api
    depends_on:
      - db
    volumes:
      - ./api:/app
    working_dir: /app
    command: ["dotnet", "run", "--urls", "http://0.0.0.0:5020"]
    ports:
      - "5020:5020"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=coursesdb;Username=dbUser;Password=dbpassword

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: course-web
    depends_on:
      - api
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://api:5020

volumes:
  postgres_data:
